"""Initial migration

Revision ID: 3ed6e6407821
Revises:
Create Date: 2025-10-22 19:42:09.950947

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "3ed6e6407821"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_summaries", schema=None) as batch_op:
        batch_op.alter_column(
            "keywords",
            existing_type=sqlite.JSON(),
            type_=sa.Text(),
            existing_nullable=True,
        )

    with op.batch_alter_table("email_threads", schema=None) as batch_op:
        batch_op.alter_column(
            "participants",
            existing_type=sqlite.JSON(),
            type_=sa.Text(),
            existing_nullable=True,
        )

    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.alter_column(
            "attachments",
            existing_type=sqlite.JSON(),
            type_=sa.Text(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "headers",
            existing_type=sqlite.JSON(),
            type_=sa.Text(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.alter_column(
            "headers",
            existing_type=sa.Text(),
            type_=sqlite.JSON(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "attachments",
            existing_type=sa.Text(),
            type_=sqlite.JSON(),
            existing_nullable=True,
        )

    with op.batch_alter_table("email_threads", schema=None) as batch_op:
        batch_op.alter_column(
            "participants",
            existing_type=sa.Text(),
            type_=sqlite.JSON(),
            existing_nullable=True,
        )

    with op.batch_alter_table("email_summaries", schema=None) as batch_op:
        batch_op.alter_column(
            "keywords",
            existing_type=sa.Text(),
            type_=sqlite.JSON(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
