"""Add is_important column to emails

Revision ID: b0c36ddf90a2
Revises: 3ed6e6407821
Create Date: 2025-10-23 11:29:55.403363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c36ddf90a2'
down_revision = '3ed6e6407821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_important', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_column('is_important')

    # ### end Alembic commands ###
