repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: ^pop3service/
      - id: end-of-file-fixer
        files: ^pop3service/
      - id: check-yaml
        files: ^pop3service/
      - id: check-added-large-files
        files: ^pop3service/
      - id: check-merge-conflict
        files: ^pop3service/
      - id: debug-statements
        files: ^pop3service/

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        files: ^pop3service/
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^pop3service/
        args: ["--profile", "black"]
