version: '3.8'

services:
  # PostgreSQL 데이터베이스
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: proxyme_email
      POSTGRES_USER: proxyme_user
      POSTGRES_PASSWORD: proxyme_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U proxyme_user -d proxyme_email"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ProxyMe Email Service
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://proxyme_user:proxyme_password@db:5432/proxyme_email
      FLASK_ENV: production
      FLASK_DEBUG: False
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
